---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apis.kcp.dev
  resources:
  - apiexports
  verbs:
  - create
  - delete
  - get
  - initialize
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apis.kcp.dev
  resources:
  - apiexports/status
  verbs:
  - get
- apiGroups:
  - data.my.domain
  resources:
  - widgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - data.my.domain
  resources:
  - widgets/finalizers
  verbs:
  - update
- apiGroups:
  - data.my.domain
  resources:
  - widgets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - tenancy.kcp.dev
  resources:
  - clusterworkspacetypes
  verbs:
  - create
  - delete
  - get
  - initialize
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tenancy.kcp.dev
  resources:
  - clusterworkspacetypes/finalizers
  verbs:
  - update
- apiGroups:
  - tenancy.kcp.dev
  resources:
  - clusterworkspacetypes/status
  verbs:
  - get
  - patch
  - update
