apiVersion: tenancy.kcp.dev/v1alpha1
kind: ClusterWorkspaceType
metadata:
  name: widget
spec:
  additionalWorkspaceLabels:
    workloads.kcp.dev/schedulable: "true"
  allowedChildren:
    any: true
  allowedParents:
    any: true
  initializer: true
